// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHKQ1PqDDKZfUDMqnkWDxfKcxg6f1e8qg',
    appId: '1:811734824827:web:fd2177c1587083c5432fde',
    messagingSenderId: '811734824827',
    projectId: 'deneme1-83eab',
    authDomain: 'deneme1-83eab.firebaseapp.com',
    storageBucket: 'deneme1-83eab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEA_MhAHqT_78xIVvAFoxWCK8M3-thoeA',
    appId: '1:811734824827:android:5994704189f7947c432fde',
    messagingSenderId: '811734824827',
    projectId: 'deneme1-83eab',
    storageBucket: 'deneme1-83eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaCfAJcWyUMGTDs1lB-I-j9oR2RNgjpU',
    appId: '1:811734824827:ios:8c14141475d9d2c2432fde',
    messagingSenderId: '811734824827',
    projectId: 'deneme1-83eab',
    storageBucket: 'deneme1-83eab.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCaCfAJcWyUMGTDs1lB-I-j9oR2RNgjpU',
    appId: '1:811734824827:ios:238b555cb3ffe963432fde',
    messagingSenderId: '811734824827',
    projectId: 'deneme1-83eab',
    storageBucket: 'deneme1-83eab.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
